<?php

use Illuminate\Database\Seeder;
use App\PostItem;

class PostItemSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('post_items')->delete();

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));

        PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));PostItem::create(array(
            'user_id' => 1,
            'title' => "Dummy title 1",
            'images' => "",
            'price' => 4000,
            'pricing' => 'monthly',
            'type' => 'apartment',
            'street_address' => 'some random street',
            'area_address' => 'some random address',
            'city_address' => 'some random city',
            'number_of_bed_room' => 2,
            'number_of_wash_room' => 1,
            'total_area' => 4000,
            'floor' => 4,
            'amenities' => json_decode("{ 'status': true }"),
            'description' => "this will be a long description",
            'logitude' => 134.342432,
            'latitude' => 123.31231,
            'is_sold' => false
        ));
    }
}
